// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhotkxknbjnevzdsdvqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJob3RreGtuYmpuZXZ6ZHNkdnFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MzU3MjIsImV4cCI6MjA2NTMxMTcyMn0.dnqzhaizWX-juvvDX-gVPeYjg6psW3W1t9TAEwHT2Jc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);